name: Main Workflow

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  # schedule:
  #   - cron: "0 0 * * 5"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: balena --help
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
